-- MySQL Script generated by MySQL Workbench
-- 04/07/16 22:27:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fcb_trackingengine
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `fcb_carrier_carrier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_carrier_carrier` ;

CREATE TABLE IF NOT EXISTS `fcb_carrier_carrier` (
  `carrierId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `creationDate` DATETIME NOT NULL,
  `alias` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`carrierId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcb_service_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_service_service` ;

CREATE TABLE IF NOT EXISTS `fcb_service_service` (
  `serviceId` INT NOT NULL AUTO_INCREMENT,
  `endpoint` VARCHAR(256) NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `editionDate` DATETIME NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Active:1, Inactive:0',
  PRIMARY KEY (`serviceId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcb_apikey_apikey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_apikey_apikey` ;

CREATE TABLE IF NOT EXISTS `fcb_apikey_apikey` (
  `apikeyId` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(250) NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `profileId` INT NOT NULL,
  PRIMARY KEY (`apikeyId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcb_statistic_service_apikey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_statistic_service_apikey` ;

CREATE TABLE IF NOT EXISTS `fcb_statistic_service_apikey` (
  `serviceApikeyId` INT NOT NULL AUTO_INCREMENT,
  `apikeyId` INT NOT NULL,
  `serviceId` INT NOT NULL,
  `counter` INT NOT NULL DEFAULT 0,
  `creationDate` DATETIME NOT NULL,
  PRIMARY KEY (`serviceApikeyId`),
  INDEX `fk_Fcb_Ts_EndPointApikey_FcbTs_Ts_ApiKey_idx` (`apikeyId` ASC),
  INDEX `fk_Fcb_Ts_ServiceApikey_Fcb_Ts_Service1_idx` (`serviceId` ASC),
  CONSTRAINT `fk_Fcb_Ts_EndPointApikey_FcbTs_Ts_ApiKey`
    FOREIGN KEY (`apikeyId`)
    REFERENCES `fcb_apikey_apikey` (`apikeyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fcb_Ts_ServiceApikey_Fcb_Ts_Service1`
    FOREIGN KEY (`serviceId`)
    REFERENCES `fcb_service_service` (`serviceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcb_service_multitracking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_service_multitracking` ;

CREATE TABLE IF NOT EXISTS `fcb_service_multitracking` (
  `multitrackingId` INT NOT NULL AUTO_INCREMENT,
  `trackingKeys` TEXT NULL,
  `apikeyId` INT NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `editionDate` DATETIME NULL,
  `token` VARCHAR(250) NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1: active, 0: inactive',
  PRIMARY KEY (`multitrackingId`),
  INDEX `fk_fcb_service_multitracking_fcb_apikey_apikey1_idx` (`apikeyId` ASC),
  CONSTRAINT `fk_fcb_service_multitracking_fcb_apikey_apikey1`
    FOREIGN KEY (`apikeyId`)
    REFERENCES `fcb_apikey_apikey` (`apikeyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcb_search_search`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_search_search` ;

CREATE TABLE IF NOT EXISTS `fcb_search_search` (
  `searchId` INT NOT NULL AUTO_INCREMENT,
  `carrierId` INT NULL,
  `serviceApikeyId` INT NOT NULL,
  `multitrackingId` INT NULL,
  `trackingKey` VARCHAR(250) NULL,
  `creationDate` DATETIME NOT NULL,
  `ip` VARCHAR(16) NULL COMMENT 'Search creator IP',
  PRIMARY KEY (`searchId`),
  INDEX `fk_fcb_search_search_fcb_carrier_carrier1_idx` (`carrierId` ASC),
  INDEX `fk_fcb_search_search_fcb_statistic_service_apikey1_idx` (`serviceApikeyId` ASC),
  INDEX `fk_fcb_search_search_fcb_service_multitracking1_idx` (`multitrackingId` ASC),
  CONSTRAINT `fk_fcb_search_search_fcb_carrier_carrier1`
    FOREIGN KEY (`carrierId`)
    REFERENCES `fcb_carrier_carrier` (`carrierId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fcb_search_search_fcb_statistic_service_apikey1`
    FOREIGN KEY (`serviceApikeyId`)
    REFERENCES `fcb_statistic_service_apikey` (`serviceApikeyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fcb_search_search_fcb_service_multitracking1`
    FOREIGN KEY (`multitrackingId`)
    REFERENCES `fcb_service_multitracking` (`multitrackingId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcb_search_track`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_search_track` ;

CREATE TABLE IF NOT EXISTS `fcb_search_track` (
  `trackId` INT NOT NULL AUTO_INCREMENT,
  `searchId` INT NOT NULL,
  `carrierId` INT NOT NULL,
  `trackingKey` VARCHAR(250) NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `editionDate` DATETIME NULL,
  `statusCreationDateTime` DATETIME NULL,
  `statusCode` VARCHAR(4) NULL,
  `statusDescription` VARCHAR(250) NULL,
  `statusLocStateOrProvinceCode` VARCHAR(4) NULL,
  `statusLocCountryCode` VARCHAR(4) NULL,
  `statusLocCountryName` VARCHAR(45) NULL,
  `track` TEXT NULL,
  PRIMARY KEY (`trackId`),
  INDEX `fk_fcb_search_track_fcb_carrier_carrier1_idx` (`carrierId` ASC),
  INDEX `fk_fcb_search_track_fcb_search_search1_idx` (`searchId` ASC),
  CONSTRAINT `fk_fcb_search_track_fcb_carrier_carrier1`
    FOREIGN KEY (`carrierId`)
    REFERENCES `fcb_carrier_carrier` (`carrierId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fcb_search_track_fcb_search_search1`
    FOREIGN KEY (`searchId`)
    REFERENCES `fcb_search_search` (`searchId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcb_carrier_request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_carrier_request` ;

CREATE TABLE IF NOT EXISTS `fcb_carrier_request` (
  `requestId` INT NOT NULL AUTO_INCREMENT,
  `searchId` INT NOT NULL,
  `request` TEXT NULL,
  `response` TEXT NULL,
  `creationDate` DATETIME NOT NULL,
  PRIMARY KEY (`requestId`),
  INDEX `fk_fcb_carrier_request_fcb_search_search1_idx` (`searchId` ASC),
  CONSTRAINT `fk_fcb_carrier_request_fcb_search_search1`
    FOREIGN KEY (`searchId`)
    REFERENCES `fcb_search_search` (`searchId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcb_carrier_coordinates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_carrier_coordinates` ;

CREATE TABLE IF NOT EXISTS `fcb_carrier_coordinates` (
  `coordinateId` INT NOT NULL AUTO_INCREMENT,
  `carrierId` INT NOT NULL,
  `code` VARCHAR(125) NULL,
  `latitud` VARCHAR(32) NULL,
  `longitud` VARCHAR(32) NULL,
  `nameCoordinate` VARCHAR(64) NULL,
  PRIMARY KEY (`coordinateId`),
  INDEX `fk_fcb_carrier_coordinates_fcb_carrier_carrier1_idx` (`carrierId` ASC),
  CONSTRAINT `fk_fcb_carrier_coordinates_fcb_carrier_carrier1`
    FOREIGN KEY (`carrierId`)
    REFERENCES `fcb_carrier_carrier` (`carrierId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcb_track_ubigeo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_track_ubigeo` ;

CREATE TABLE IF NOT EXISTS `fcb_track_ubigeo` (
  `ubigeoId` INT NOT NULL AUTO_INCREMENT,
  `stateOrPronviceCode` VARCHAR(45) NULL,
  `countryCode` VARCHAR(45) NULL,
  `StateOrPronvinceName` VARCHAR(45) NULL,
  `countryName` VARCHAR(45) NULL,
  `latitud` VARCHAR(45) NULL,
  `longitud` VARCHAR(45) NULL,
  PRIMARY KEY (`ubigeoId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcb_track_track`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_track_track` ;

CREATE TABLE IF NOT EXISTS `fcb_track_track` (
  `trackId` INT NOT NULL AUTO_INCREMENT,
  `trackingKey` VARCHAR(32) NULL,
  `creationDate` DATETIME NOT NULL COMMENT 'Row creation date',
  `editionDate` DATETIME NULL COMMENT 'Row edition date',
  `carrierCode` VARCHAR(16) NULL,
  `operatingCompanyOrCarrierDescription` VARCHAR(64) NULL,
  `originStateOrProvinceCode` VARCHAR(32) NULL,
  `originCountryCode` VARCHAR(32) NULL,
  `originCountryName` VARCHAR(64) NULL,
  `destinationStateOrProvinceCode` VARCHAR(32) NULL,
  `destinationCountryCode` VARCHAR(32) NULL,
  `destinationCountryName` VARCHAR(54) NULL,
  `originUbigeoId` INT NULL,
  `destinationUbigeoId` INT NULL,
  PRIMARY KEY (`trackId`),
  INDEX `fk_fcb_track_track_fcb_track_ubigeo1_idx` (`originUbigeoId` ASC),
  INDEX `fk_fcb_track_track_fcb_track_ubigeo2_idx` (`destinationUbigeoId` ASC),
  CONSTRAINT `fk_fcb_track_track_fcb_track_ubigeo1`
    FOREIGN KEY (`originUbigeoId`)
    REFERENCES `fcb_track_ubigeo` (`ubigeoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fcb_track_track_fcb_track_ubigeo2`
    FOREIGN KEY (`destinationUbigeoId`)
    REFERENCES `fcb_track_ubigeo` (`ubigeoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcb_service_request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_service_request` ;

CREATE TABLE IF NOT EXISTS `fcb_service_request` (
  `serviceRequestId` INT NOT NULL AUTO_INCREMENT,
  `trackId` INT NOT NULL,
  `serviceApikeyId` INT NOT NULL,
  `request` TEXT NOT NULL,
  `creationDate` DATETIME NOT NULL COMMENT 'Rrow creation date',
  PRIMARY KEY (`serviceRequestId`),
  INDEX `fk_fcb_service_request_fcb_track_track1_idx` (`trackId` ASC),
  INDEX `fk_fcb_service_request_fcb_statistic_service_apikey1_idx` (`serviceApikeyId` ASC),
  CONSTRAINT `fk_fcb_service_request_fcb_track_track1`
    FOREIGN KEY (`trackId`)
    REFERENCES `fcb_track_track` (`trackId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fcb_service_request_fcb_statistic_service_apikey1`
    FOREIGN KEY (`serviceApikeyId`)
    REFERENCES `fcb_statistic_service_apikey` (`serviceApikeyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcb_track_event_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_track_event_status` ;

CREATE TABLE IF NOT EXISTS `fcb_track_event_status` (
  `eventStatusId` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(4) NULL,
  `description` VARCHAR(200) NULL,
  PRIMARY KEY (`eventStatusId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcb_track_event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_track_event` ;

CREATE TABLE IF NOT EXISTS `fcb_track_event` (
  `eventId` INT NOT NULL AUTO_INCREMENT,
  `trackId` INT NOT NULL,
  `eventStatusId` INT NOT NULL,
  `creationDate` DATETIME NOT NULL COMMENT 'Row creation date',
  `editionDate` DATETIME NULL COMMENT 'Row edition date',
  `date` DATETIME NULL,
  `eventDescription` VARCHAR(200) NULL,
  `postalCode` VARCHAR(16) NULL,
  `stateProvinceCode` VARCHAR(16) NULL,
  `countryName` VARCHAR(64) NULL,
  `countryCode` VARCHAR(4) NULL,
  `latitud` VARCHAR(16) NULL,
  `longitud` VARCHAR(16) NULL,
  `ubigeoId` INT NULL,
  PRIMARY KEY (`eventId`, `trackId`),
  INDEX `fk_fcb_track_event_fcb_track_track1_idx` (`trackId` ASC),
  INDEX `fk_fcb_track_event_fcb_track_event_status1_idx` (`eventStatusId` ASC),
  INDEX `fk_fcb_track_event_fcb_track_ubigeo1_idx` (`ubigeoId` ASC),
  CONSTRAINT `fk_fcb_track_event_fcb_track_track1`
    FOREIGN KEY (`trackId`)
    REFERENCES `fcb_track_track` (`trackId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fcb_track_event_fcb_track_event_status1`
    FOREIGN KEY (`eventStatusId`)
    REFERENCES `fcb_track_event_status` (`eventStatusId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fcb_track_event_fcb_track_ubigeo1`
    FOREIGN KEY (`ubigeoId`)
    REFERENCES `fcb_track_ubigeo` (`ubigeoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcb_track_shipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_track_shipment` ;

CREATE TABLE IF NOT EXISTS `fcb_track_shipment` (
  `trackId` INT NOT NULL,
  `shipmentId` INT NOT NULL AUTO_INCREMENT,
  `weightValue` FLOAT NULL,
  `weightUnits` FLOAT NULL,
  `dimensionLength` FLOAT NULL,
  `dimensionWidth` FLOAT NULL,
  `dimensionHeight` FLOAT NULL,
  `dimensionUnits` FLOAT NULL,
  `numberOfPieces` INT NULL,
  `packageSequenceNumber` FLOAT NULL,
  `packaging` VARCHAR(64) NULL,
  `service` VARCHAR(200) NULL,
  `pickupDate` DATETIME NULL,
  `lastUpdated` DATETIME NULL,
  `creationDate` DATETIME NOT NULL COMMENT 'Row creationDate',
  `editionDate` DATETIME NULL COMMENT 'Row Edition date',
  PRIMARY KEY (`shipmentId`),
  INDEX `fk_fcb_track_shipment_fcb_track_track1_idx` (`trackId` ASC),
  CONSTRAINT `fk_fcb_track_shipment_fcb_track_track1`
    FOREIGN KEY (`trackId`)
    REFERENCES `fcb_track_track` (`trackId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
