-- MySQL Script generated by MySQL Workbench
-- 03/11/16 13:58:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fcb_accountmanager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `fcb_account_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_account_account` ;

CREATE TABLE IF NOT EXISTS `fcb_account_account` (
  `accountId` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(250) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `editionDate` DATETIME NULL,
  `status` TINYINT(1) NULL,
  PRIMARY KEY (`accountId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcb_account_profile_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_account_profile_type` ;

CREATE TABLE IF NOT EXISTS `fcb_account_profile_type` (
  `profileTypeId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`profileTypeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcb_account_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_account_profile` ;

CREATE TABLE IF NOT EXISTS `fcb_account_profile` (
  `profileId` INT NOT NULL AUTO_INCREMENT,
  `accountId` INT NOT NULL,
  `profileTypeId` INT NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '0:inactive, 1:active: 2: banned',
  PRIMARY KEY (`profileId`),
  INDEX `fk_table1_fcb_account_account_idx` (`accountId` ASC),
  INDEX `fk_table1_fcb_account_profile_type1_idx` (`profileTypeId` ASC),
  CONSTRAINT `fk_table1_fcb_account_account`
    FOREIGN KEY (`accountId`)
    REFERENCES `fcb_account_account` (`accountId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_fcb_account_profile_type1`
    FOREIGN KEY (`profileTypeId`)
    REFERENCES `fcb_account_profile_type` (`profileTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcb_apikey_environment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_apikey_environment` ;

CREATE TABLE IF NOT EXISTS `fcb_apikey_environment` (
  `environmentId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`environmentId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcb_apikey_apikey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_apikey_apikey` ;

CREATE TABLE IF NOT EXISTS `fcb_apikey_apikey` (
  `apikeyId` INT NOT NULL AUTO_INCREMENT,
  `environmentId` INT NOT NULL,
  `profileId` INT NOT NULL,
  `key` VARCHAR(250) NOT NULL,
  `creationDate` DATETIME NOT NULL,
  PRIMARY KEY (`apikeyId`),
  INDEX `fk_fcb_apikey_apikey_fcb_apikey_environment1_idx` (`environmentId` ASC),
  INDEX `fk_fcb_apikey_apikey_fcb_account_profile1_idx` (`profileId` ASC),
  CONSTRAINT `fk_fcb_apikey_apikey_fcb_apikey_environment1`
    FOREIGN KEY (`environmentId`)
    REFERENCES `fcb_apikey_environment` (`environmentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fcb_apikey_apikey_fcb_account_profile1`
    FOREIGN KEY (`profileId`)
    REFERENCES `fcb_account_profile` (`profileId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcb_service_project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_service_project` ;

CREATE TABLE IF NOT EXISTS `fcb_service_project` (
  `projectId` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`projectId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcb_service_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_service_service` ;

CREATE TABLE IF NOT EXISTS `fcb_service_service` (
  `serviceId` INT NOT NULL AUTO_INCREMENT,
  `projectId` INT NOT NULL,
  `endpoint` VARCHAR(250) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `creationDate` DATETIME NOT NULL,
  `editionDate` DATETIME NULL,
  PRIMARY KEY (`serviceId`),
  INDEX `fk_fcb_service_service_fcb_service_project1_idx` (`projectId` ASC),
  CONSTRAINT `fk_fcb_service_service_fcb_service_project1`
    FOREIGN KEY (`projectId`)
    REFERENCES `fcb_service_project` (`projectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcb_statistic_service_apikey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcb_statistic_service_apikey` ;

CREATE TABLE IF NOT EXISTS `fcb_statistic_service_apikey` (
  `serviceApikeyId` INT NOT NULL AUTO_INCREMENT,
  `apikeyId` INT NOT NULL,
  `serviceId` INT NOT NULL,
  `counter` INT NOT NULL DEFAULT 0,
  `creationDate` DATETIME NOT NULL,
  PRIMARY KEY (`serviceApikeyId`),
  INDEX `fk_fcb_service_apikey_fcb_apikey_apikey1_idx` (`apikeyId` ASC),
  INDEX `fk_fcb_service_apikey_fcb_service_service1_idx` (`serviceId` ASC),
  CONSTRAINT `fk_fcb_service_apikey_fcb_apikey_apikey1`
    FOREIGN KEY (`apikeyId`)
    REFERENCES `fcb_apikey_apikey` (`apikeyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fcb_service_apikey_fcb_service_service1`
    FOREIGN KEY (`serviceId`)
    REFERENCES `fcb_service_service` (`serviceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
