<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
        'DoctrineModule',
        'DoctrineORMModule',
        'Search',
        'Carrier',
        'Statistic',
        'Service',
        'Api',
        'Application',
        'Apikey',
        'Test',
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor',
            './ws',
        ),
        'config_glob_paths' => array(
            'config/autoload/{{,*.}global,{,*.}local}.php',
        ),
    ),
);
